// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcslbtsxmctxkudozrck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjc2xidHN4bWN0eGt1ZG96cmNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNDUyMjAsImV4cCI6MjA2MTcyMTIyMH0.wkJB4TFho1QqFQSGD__Ot_Tjl-52KKMl4-XtUQFedEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);